project_id = "nxmsdrnxrpgmrzprpzij"

[functions.generate-script]
verify_jwt = false

[functions.strategic-analysis]
verify_jwt = false

[functions.process-briefing]
verify_jwt = false

[functions.manual-generate]
verify_jwt = false

[functions.generate-ideas]
verify_jwt = false

[functions.generate-hooks]
verify_jwt = false

[functions.score-script]
verify_jwt = false

[functions.suggest-briefing]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false
