// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iztxtioenssaujycldek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6dHh0aW9lbnNzYXVqeWNsZGVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0NTI2NjIsImV4cCI6MjA4MDAyODY2Mn0.PCZBzuJnmQsxoQcqJuV5U027wT5TYCl9aeldgD8UsGI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});